### ISSUE TITLE
Publish as steam mod

### ISSUE THREAD

**Issue by Bluscream** [ampersand38/Arma-3-Breaching-Charge#3]
please

**Comment by ampersand38** [comment]
Already is =p
https://steamcommunity.com/sharedfiles/filedetails/?id=1314910827
https://forums.bohemia.net/forums/topic/215148-breaching-charge/

How did you find this on GitHub if not through one of those places?

**Comment by Bluscream** [comment]
Through https://www.google.com/search?client=firefox-b-d&q="getdoor"+ace+arma apparently ^^
