### ISSUE TITLE
Add ACE interaction items for breaching

### ISSUE THREAD

**Issue by Bluscream** [ampersand38/Arma-3-Breaching-Charge#5]
I didn't really expect you to be active here ^^ but now that i know you are:

https://ace3mod.com/wiki/framework/interactionMenu-framework.html

**Comment by ampersand38** [comment]
I'm not sure what your goal here is. Everything is run through ACE Explosives. Try it out or check the video linked in Steam/BI Forums.

**Comment by Bluscream** [comment]
Yeah, i saw that but i think it would be easier if there was a simple `Breach` item in the interaction menu that would plant the charge, play "lean on wall next to door" animation and boom. This would also incorporate well with my next suggestion

**Comment by Bluscream** [comment]
Possibly helpful resources:
- https://github.com/acemod/ACE3/blob/master/addons/interaction/functions/fnc_openDoor.sqf
- https://github.com/acemod/ACE3/blob/master/addons/interaction/functions/fnc_getDoor.sqf
- https://github.com/acemod/ACE3/blob/master/addons/interaction/XEH_postInit.sqf#L95
- https://github.com/acemod/ACE3/blob/master/addons/interact_menu/functions/fnc_userActions_addHouseActions.sqf#L77-L94
- https://github.com/acemod/ACE3/blob/master/addons/interact_menu/functions/fnc_userActions_getHouseActions.sqf

**Comment by ampersand38** [comment]
The ACE Explosives approach allows for more control, and multiple simultaneous breaches using clacker or synced timers. I don't think taking over player movement would be a good idea.

**Comment by Bluscream** [comment]
You're probably right c:
